apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cicd-demo-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/hrithik-k0/cicd-demo-manifests.git
    targetRevision: main
    path: base

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true      # remove resources that are no longer in git
      selfHeal: true    # revert manual cluster changes back to match git
    syncOptions:
      - CreateNamespace=true
